
package vista;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Walla Peguero
 */
public class Login extends javax.swing.JFrame {

    
    public Login() {
        initComponents();
        this.setTitle("Save The Pets"); // Titulo del Software
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/huella.png")).getImage()); //Imagen para el soft
        setLocationRelativeTo(null); // Funcion para que la ventana aparezca centralizada
        pnlAcceder.requestFocusInWindow(); // Funcion para darle el Focus a PnlAcceder        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlFondo = new javax.swing.JPanel();
        pnlAcceder = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ImgContra = new javax.swing.JLabel();
        ImgLogin = new javax.swing.JLabel();
        lblOlvidoContra = new javax.swing.JLabel();
        lblSeparador = new javax.swing.JLabel();
        lblCreditos = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        lblLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        pnlFondo.setBackground(new java.awt.Color(15, 15, 15));
        pnlFondo.setPreferredSize(new java.awt.Dimension(800, 500));
        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlAcceder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlAccederMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlAccederMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ACCEDER");

        javax.swing.GroupLayout pnlAccederLayout = new javax.swing.GroupLayout(pnlAcceder);
        pnlAcceder.setLayout(pnlAccederLayout);
        pnlAccederLayout.setHorizontalGroup(
            pnlAccederLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccederLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        pnlAccederLayout.setVerticalGroup(
            pnlAccederLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlFondo.add(pnlAcceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 380, 40));

        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        pnlFondo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 420, 30));

        ImgContra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImgContra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Password.png"))); // NOI18N
        pnlFondo.add(ImgContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 30, 30));

        ImgLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user (2).png"))); // NOI18N
        ImgLogin.setPreferredSize(new java.awt.Dimension(30, 30));
        pnlFondo.add(ImgLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        lblOlvidoContra.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblOlvidoContra.setForeground(new java.awt.Color(255, 255, 255));
        lblOlvidoContra.setText("¿Has olvidado tu contraseña?");
        lblOlvidoContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOlvidoContraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOlvidoContraMouseExited(evt);
            }
        });
        pnlFondo.add(lblOlvidoContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 200, 20));

        lblSeparador.setForeground(new java.awt.Color(255, 255, 255));
        lblSeparador.setText("________________________________________");
        lblSeparador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSeparadorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSeparadorMouseExited(evt);
            }
        });
        pnlFondo.add(lblSeparador, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 200, 50));

        lblCreditos.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblCreditos.setForeground(new java.awt.Color(105, 105, 105));
        lblCreditos.setText("© Creado y Diseñado Por SpeedSoft");
        pnlFondo.add(lblCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, -1, -1));

        txtUsuario.setBackground(new java.awt.Color(15, 15, 15));
        txtUsuario.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(105, 105, 105));
        txtUsuario.setText("USUARIO");
        txtUsuario.setBorder(null);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        pnlFondo.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 420, -1));

        txtContraseña.setBackground(new java.awt.Color(15, 15, 15));
        txtContraseña.setForeground(new java.awt.Color(105, 105, 105));
        txtContraseña.setText("**********");
        txtContraseña.setBorder(null);
        txtContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtContraseñaMousePressed(evt);
            }
        });
        pnlFondo.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 420, -1));
        pnlFondo.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 420, 30));

        lblLogin.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(105, 105, 105));
        lblLogin.setText("LOGIN");
        pnlFondo.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 130, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/DOG ANIMADO.png"))); // NOI18N
        pnlFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 350, 350));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BlobsVector.png"))); // NOI18N
        pnlFondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 300, 260));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BlobsVector-1.png"))); // NOI18N
        pnlFondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 280, 320));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BlobsVector-2.png"))); // NOI18N
        pnlFondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 270, 230));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Vector.png"))); // NOI18N
        pnlFondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 280, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 962, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cambiarColores(boolean esMouseDentro) {
    // Cambiar el color dependiendo si el mouse está dentro o no
    Color color = esMouseDentro ? new Color(116, 116, 116) : new Color(255, 255, 255);

    lblOlvidoContra.setForeground(color);
    lblSeparador.setForeground(color);
}

    private void pnlAccederMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAccederMouseEntered
        pnlAcceder.setBackground(new Color(116,116,116));
    }//GEN-LAST:event_pnlAccederMouseEntered

    private void pnlAccederMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAccederMouseExited
        pnlAcceder.setBackground(new Color(40,40,40));
    }//GEN-LAST:event_pnlAccederMouseExited

    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed
          if (txtUsuario.getText().equals("USUARIO")) {
            txtUsuario.setText("");
            txtUsuario.setForeground(Color.white);
        }
        if(String.valueOf(txtContraseña.getPassword()).isEmpty()) {
            txtContraseña.setText("**********");
            txtContraseña.setForeground(Color.gray);
    }//GEN-LAST:event_txtUsuarioMousePressed
}
    private void txtContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraseñaMousePressed
          if(String.valueOf(txtContraseña.getPassword()).equals("**********")) {
            txtContraseña.setText("");
            txtContraseña.setForeground(Color.white);
        }
        if (txtUsuario.getText().isEmpty()) {
            txtUsuario.setText("USUARIO");
            txtUsuario.setForeground(Color.gray);
    }//GEN-LAST:event_txtContraseñaMousePressed
}
    private void lblOlvidoContraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOlvidoContraMouseEntered
        cambiarColores(true);
    }//GEN-LAST:event_lblOlvidoContraMouseEntered

    private void lblOlvidoContraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOlvidoContraMouseExited
        cambiarColores(false);
    }//GEN-LAST:event_lblOlvidoContraMouseExited

    private void lblSeparadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSeparadorMouseEntered
        cambiarColores(true);
    }//GEN-LAST:event_lblSeparadorMouseEntered

    private void lblSeparadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSeparadorMouseExited
        cambiarColores(false);
    }//GEN-LAST:event_lblSeparadorMouseExited


    
     /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImgContra;
    private javax.swing.JLabel ImgLogin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblCreditos;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblOlvidoContra;
    private javax.swing.JLabel lblSeparador;
    private javax.swing.JPanel pnlAcceder;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
