package vista;

/**
 * Panel que representa la sección de Instrucciones 2 del manual de usuario.
 * @author Walla Peguero
 */
public class ManualDeUsuario3 extends javax.swing.JPanel {

    /**
     * Creates new form ManualDeUsuario3
     */
    /**
     * Constructor del panel ManualDeUsuario3.
     * Inicializa los componentes y establece el foco en la etiqueta de título.
     */
    public ManualDeUsuario3() {
        initComponents();
        lblTitulo.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        jTextArea1.setBackground(new java.awt.Color(15, 15, 15));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("1. Introducción:\n\nEl programa \" Save the Pets \" es una herramienta desarrollada en Java para\ngestionar y monitorear el ingreso de animales en un refugio de animales. Su diseño\nintuitivo y funcionalidad eficiente permiten llevar un control preciso y actualizado\nsobre el estado de los animales que se encuentren en el refugio.\n\nObjetivos:\n\nFacilitar la administración de registros de entrada de animales.\nGarantizar un manejo seguro y ordenado de los animales.\nPúblico objetivo: Personal administrativo o de logística encargado del registro y\nmonitoreo de los animales.\n\n2. Requisitos del Sistema:\n\nSistema Operativo: Windows, macOS o Linux.\nNetBeans IDE 22: JDK 23.\nEspacio en disco: 50 MB.\nRAM: Mínimo 512 MB.\n\n3. Instalación:\n\nDescargue el archivo Save-The-Pets.jar desde el enlace proporcionado.\nAsegúrese de tener instalado Java.\n");
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setBackground(new java.awt.Color(15, 15, 15));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setRows(5);
        jTextArea2.setText("1. Introducción:\n\nEl programa \" Save the Pets \" es una herramienta desarrollada en Java para\ngestionar y monitorear el ingreso de animales en un refugio de animales. Su diseño\nintuitivo y funcionalidad eficiente permiten llevar un control preciso y actualizado\nsobre el estado de los animales que se encuentren en el refugio.\n\nObjetivos:\n\nFacilitar la administración de registros de entrada de animales.\nGarantizar un manejo seguro y ordenado de los animales.\nPúblico objetivo: Personal administrativo o de logística encargado del registro y\nmonitoreo de los animales.\n\n2. Requisitos del Sistema:\n\nSistema Operativo: Windows, macOS o Linux.\nNetBeans IDE 22: JDK 23.\nEspacio en disco: 50 MB.\nRAM: Mínimo 512 MB.\n\n3. Instalación:\n\nDescargue el archivo Save-The-Pets.jar desde el enlace proporcionado.\nAsegúrese de tener instalado Java.\n");
        jScrollPane2.setViewportView(jTextArea2);

        setBackground(new java.awt.Color(15, 15, 15));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Instrucciones de Uso \"Save the Pets\"");
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 277, 50));

        jTextArea3.setBackground(new java.awt.Color(15, 15, 15));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea3.setRows(5);
        jTextArea3.setText("Pantalla Principal:\n\nObjetivo: servir de intermediario entre las \ndiferentes partes del programa\nOpciones:\nMascotas. (Formulario Mascotas)\nAcerca de. (Información del Programa)\nExit (Cerrar sesión)");
        jScrollPane3.setViewportView(jTextArea3);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 56, 283, 149));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pprincipal.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 25, 310, 170));

        jTextArea4.setBackground(new java.awt.Color(15, 15, 15));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTextArea4.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea4.setRows(5);
        jTextArea4.setText(" Mascotas: Registro de animales\n\n-Para Ingresar un nuevo animal al registro:\n1. Complete los campos requeridos:\n● ID /Clave.\n● Nombre.\n● Sexo: Macho, Hembra o Hermafrodita.\n● Peso kg.\n● Especie: Perro, Gato u Otras.\n● Raza.\n● Estado de Vacunación: True o False.\n● Estado de adopción: True o False.\n● Ingresado por.\n2. Presione el botón \"Guardar\".\n\n-Para eliminar un animal del registro:\n1. Haga Click sobre el registro que desee \neliminar.\n2. Presione el botón con el icono del contenedor \nde basura.\n\n-Para actualizar un animal del registro:\n1. Haga Click sobre el registro que desee\n actualizar.\n2. Presione el botón “Editar”.\n3. Edite los campos que desee modificar.\n4. Presione el botón “Actualizar”.\n\n-Para buscar un animal en el registro:\n1. Haga Click en el panel que dice “Buscar”.\n2. Escriba el nombre o alguna de las características \ndel animal que quiera\nbuscar.\n3. Haga Click en el botón con el icono de lupa para\n ver los registros de lo\nanimales.\n\nAnimales inscritos:\nMuestra los animales registrados.\nOpciones:\n● Guardar: Ingrese los datos del nuevo animal haga\n clic en “Guardar”.\n● Editar: Seleccione un registro y haga clic en \"Editar\".\n● Actualizar: Guarde los cambios haciendo click en \n“Actualizar”.\n● Eliminar: Seleccione un registro y haga clic en\n \"Eliminar\".\n● Buscar: Escriba lo que quiere buscar y haga click en \nel botón con la lupa.\n\nBotones disponibles:\n● Agregar: Para registrar nuevos animales.\n● Editar: Para editar registros.\n● Cancelar: Para cancelar un registro.\n● Actualizar: Para guardar los cambios en el registro.\n● Buscar: Para buscar un animal.\n● Eliminar: Para eliminar un animal.");
        jTextArea4.setCaretPosition(0);
        jScrollPane4.setViewportView(jTextArea4);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 283, 164));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FormMascota.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 210, 310, 170));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
