/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatArcDarkIJTheme;
import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Walla Peguero
 */
public class ManualDeUsuario extends javax.swing.JFrame {

    /**
     * Creates new form ManualDeUsuario
     */
    public ManualDeUsuario() {
        initComponents();
        pnlSuperior.requestFocus();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/huella.png")).getImage()); //Imagen para el soft
        this.setTitle("Manual De Usuario");
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); //Cerrar Ventana

        //Codigo para meter un Jpanel dentro de otro
        ManualDeUsuario1 manual1 = new ManualDeUsuario1();
        manual1.setSize(640, 390);
        manual1.setLocation(0, 0);

        content.removeAll();
        content.add(manual1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backGround = new javax.swing.JPanel();
        pnlSuperior = new javax.swing.JPanel();
        MDU1 = new javax.swing.JButton();
        MDU2 = new javax.swing.JButton();
        MDU3 = new javax.swing.JButton();
        MDU4 = new javax.swing.JButton();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSuperior.setBackground(new java.awt.Color(0, 122, 204));

        MDU1.setText("INTRODUCCION");
        MDU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MDU1ActionPerformed(evt);
            }
        });

        MDU2.setText("INSTRUCCIONES 1");
        MDU2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MDU2ActionPerformed(evt);
            }
        });

        MDU3.setText("INSTRUCCIONES 2");
        MDU3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MDU3ActionPerformed(evt);
            }
        });

        MDU4.setText("Solucion de Problemas Comunes");
        MDU4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MDU4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSuperiorLayout = new javax.swing.GroupLayout(pnlSuperior);
        pnlSuperior.setLayout(pnlSuperiorLayout);
        pnlSuperiorLayout.setHorizontalGroup(
            pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MDU1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MDU2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MDU3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MDU4)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pnlSuperiorLayout.setVerticalGroup(
            pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSuperiorLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MDU1)
                    .addComponent(MDU2)
                    .addComponent(MDU3)
                    .addComponent(MDU4))
                .addContainerGap())
        );

        backGround.add(pnlSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 50));

        content.setBackground(new java.awt.Color(15, 15, 15));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        backGround.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 640, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MDU1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MDU1ActionPerformed

        ManualDeUsuario1 manual1 = new ManualDeUsuario1();
        manual1.setSize(640, 390);
        manual1.setLocation(0, 0);

        content.removeAll();
        content.add(manual1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_MDU1ActionPerformed

    private void MDU2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MDU2ActionPerformed
        ManualDeUsuario2 manual2 = new ManualDeUsuario2();
        manual2.setSize(640, 390);
        manual2.setLocation(0, 0);

        content.removeAll();
        content.add(manual2, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_MDU2ActionPerformed

    private void MDU3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MDU3ActionPerformed
        ManualDeUsuario3 manual3 = new ManualDeUsuario3();
        manual3.setSize(640, 390);
        manual3.setLocation(0, 0);

        content.removeAll();
        content.add(manual3, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_MDU3ActionPerformed

    private void MDU4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MDU4ActionPerformed
        ManualDeUsuario4 manual4 = new ManualDeUsuario4();
        manual4.setSize(640, 390);
        manual4.setLocation(0, 0);

        content.removeAll();
        content.add(manual4, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_MDU4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManualDeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManualDeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManualDeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManualDeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatArcDarkIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManualDeUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MDU1;
    private javax.swing.JButton MDU2;
    private javax.swing.JButton MDU3;
    private javax.swing.JButton MDU4;
    private javax.swing.JPanel backGround;
    private javax.swing.JPanel content;
    private javax.swing.JPanel pnlSuperior;
    // End of variables declaration//GEN-END:variables
}
