
package vista;


/**
 *
 * @author Walla Peguero
 */
public class ManualDeUsuario4 extends javax.swing.JPanel {

    /**
     * Creates new form ManualDeUsuario2
     */
    public ManualDeUsuario4() {
        initComponents();
        lblTitulo.requestFocus();
    }
          

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        jTextArea1.setBackground(new java.awt.Color(15, 15, 15));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("1. Introducción:\n\nEl programa \" Save the Pets \" es una herramienta desarrollada en Java para\ngestionar y monitorear el ingreso de animales en un refugio de animales. Su diseño\nintuitivo y funcionalidad eficiente permiten llevar un control preciso y actualizado\nsobre el estado de los animales que se encuentren en el refugio.\n\nObjetivos:\n\nFacilitar la administración de registros de entrada de animales.\nGarantizar un manejo seguro y ordenado de los animales.\nPúblico objetivo: Personal administrativo o de logística encargado del registro y\nmonitoreo de los animales.\n\n2. Requisitos del Sistema:\n\nSistema Operativo: Windows, macOS o Linux.\nNetBeans IDE 22: JDK 23.\nEspacio en disco: 50 MB.\nRAM: Mínimo 512 MB.\n\n3. Instalación:\n\nDescargue el archivo Save-The-Pets.jar desde el enlace proporcionado.\nAsegúrese de tener instalado Java.\n");
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setBackground(new java.awt.Color(15, 15, 15));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setRows(5);
        jTextArea2.setText("1. Introducción:\n\nEl programa \" Save the Pets \" es una herramienta desarrollada en Java para\ngestionar y monitorear el ingreso de animales en un refugio de animales. Su diseño\nintuitivo y funcionalidad eficiente permiten llevar un control preciso y actualizado\nsobre el estado de los animales que se encuentren en el refugio.\n\nObjetivos:\n\nFacilitar la administración de registros de entrada de animales.\nGarantizar un manejo seguro y ordenado de los animales.\nPúblico objetivo: Personal administrativo o de logística encargado del registro y\nmonitoreo de los animales.\n\n2. Requisitos del Sistema:\n\nSistema Operativo: Windows, macOS o Linux.\nNetBeans IDE 22: JDK 23.\nEspacio en disco: 50 MB.\nRAM: Mínimo 512 MB.\n\n3. Instalación:\n\nDescargue el archivo Save-The-Pets.jar desde el enlace proporcionado.\nAsegúrese de tener instalado Java.\n");
        jScrollPane2.setViewportView(jTextArea2);

        setBackground(new java.awt.Color(15, 15, 15));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Solución de problemas comunes \"Save the Pets\"");
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 341, 50));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Causa Posible");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 92, 178, 38));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Problema");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 93, 178, 38));

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Solucion");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 92, 178, 38));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("El programa no inicia.");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 148, 177, 46));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Instalar o usar el JDK 23 en su ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 177, 46));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Versión del JDK incorrecta. ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 177, 46));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" NetBeans.");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 68, -1));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mensaje: Error de conexión... ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 177, 46));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("esta incorrecta");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 177, 46));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Colocar la dirección de la base ");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 177, 30));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(" de datos del proyecto.");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 130, -1));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("La dirección de la base de datos esta incorrecta");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 177, 46));

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Verifique y vuelva a intentarlo.");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 177, 30));

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Usuario o contraseña inválidos ");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 177, 46));

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("incorrectas\"");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 296, 130, 40));

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Mensaje: \"Credenciales ");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 140, 46));
    }// </editor-fold>//GEN-END:initComponents

                

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
