package vista;

/**
 * Panel que representa la sección de Instrucciones 1 del manual de usuario.
 * @author Walla Peguero
 */
public class ManualDeUsuario2 extends javax.swing.JPanel {

    /**
     * Creates new form ManualDeUsuario2
     */
    /**
     * Constructor del panel ManualDeUsuario2.
     * Inicializa los componentes y establece el foco en la etiqueta de título.
     */
    public ManualDeUsuario2() {
        initComponents();
        lblTitulo.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        jTextArea1.setBackground(new java.awt.Color(15, 15, 15));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("1. Introducción:\n\nEl programa \" Save the Pets \" es una herramienta desarrollada en Java para\ngestionar y monitorear el ingreso de animales en un refugio de animales. Su diseño\nintuitivo y funcionalidad eficiente permiten llevar un control preciso y actualizado\nsobre el estado de los animales que se encuentren en el refugio.\n\nObjetivos:\n\nFacilitar la administración de registros de entrada de animales.\nGarantizar un manejo seguro y ordenado de los animales.\nPúblico objetivo: Personal administrativo o de logística encargado del registro y\nmonitoreo de los animales.\n\n2. Requisitos del Sistema:\n\nSistema Operativo: Windows, macOS o Linux.\nNetBeans IDE 22: JDK 23.\nEspacio en disco: 50 MB.\nRAM: Mínimo 512 MB.\n\n3. Instalación:\n\nDescargue el archivo Save-The-Pets.jar desde el enlace proporcionado.\nAsegúrese de tener instalado Java.\n");
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setBackground(new java.awt.Color(15, 15, 15));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setRows(5);
        jTextArea2.setText("1. Introducción:\n\nEl programa \" Save the Pets \" es una herramienta desarrollada en Java para\ngestionar y monitorear el ingreso de animales en un refugio de animales. Su diseño\nintuitivo y funcionalidad eficiente permiten llevar un control preciso y actualizado\nsobre el estado de los animales que se encuentren en el refugio.\n\nObjetivos:\n\nFacilitar la administración de registros de entrada de animales.\nGarantizar un manejo seguro y ordenado de los animales.\nPúblico objetivo: Personal administrativo o de logística encargado del registro y\nmonitoreo de los animales.\n\n2. Requisitos del Sistema:\n\nSistema Operativo: Windows, macOS o Linux.\nNetBeans IDE 22: JDK 23.\nEspacio en disco: 50 MB.\nRAM: Mínimo 512 MB.\n\n3. Instalación:\n\nDescargue el archivo Save-The-Pets.jar desde el enlace proporcionado.\nAsegúrese de tener instalado Java.\n");
        jScrollPane2.setViewportView(jTextArea2);

        setBackground(new java.awt.Color(15, 15, 15));

        lblTitulo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Instrucciones de Uso \"Save the Pets\"");

        jTextArea3.setBackground(new java.awt.Color(15, 15, 15));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea3.setRows(5);
        jTextArea3.setText("Pantalla de Carga:\n\nAl iniciar el programa, se mostrará una pantalla\nde carga con el nombre del\nprograma.\nNo requiere interacción del usuario.\nDuración estimada: 5 segundos.");
        jScrollPane3.setViewportView(jTextArea3);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pcarga.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jTextArea4.setBackground(new java.awt.Color(15, 15, 15));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTextArea4.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea4.setRows(5);
        jTextArea4.setText("Pantalla de Login:\n\nObjetivos: Validar el acceso al sistema.\nPasos:\nIntroduzca su nombre de usuario en el primer \ncampo.\nIntroduzca su contraseña en el segundo campo.\nHaga clic en el botón \"ACCEDER\".\nErrores comunes:\nMensaje: \"Usuario o contraseña incorrectos\". \nSolución: Verifique las credenciales\nproporcionadas.");
        jTextArea4.setCaretPosition(0);
        jScrollPane4.setViewportView(jTextArea4);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PLogin.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
