/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatArcDarkIJTheme;
import java.awt.Color;

/**
 *
 * @author Walla Peguero
 */
public class PrincipalPrincipal extends javax.swing.JFrame {
   
    /**
     * Creates new form PrincipalPrincipal
     */
    public PrincipalPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Pet Shop Management System");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ImgSalir = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblSalidas = new javax.swing.JLabel();
        lblEntradas = new javax.swing.JLabel();
        lblMascotas = new javax.swing.JLabel();
        lblAcercaDe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImgSalir.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        ImgSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/image salida 36x36.png"))); // NOI18N
        ImgSalir.setText("Exit");
        ImgSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImgSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ImgSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ImgSalirMouseExited(evt);
            }
        });
        jPanel1.add(ImgSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, -1, -1));

        lblSalidas.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblSalidas.setForeground(new java.awt.Color(255, 255, 255));
        lblSalidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Stock Index Up_32x32.png"))); // NOI18N
        lblSalidas.setText("Salidas");
        lblSalidas.setPreferredSize(new java.awt.Dimension(150, 150));
        lblSalidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSalidasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalidasMouseExited(evt);
            }
        });

        lblEntradas.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblEntradas.setForeground(new java.awt.Color(255, 255, 255));
        lblEntradas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Stock Index Down_32x32.png"))); // NOI18N
        lblEntradas.setText("Entradas");
        lblEntradas.setPreferredSize(new java.awt.Dimension(150, 150));
        lblEntradas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEntradasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEntradasMouseExited(evt);
            }
        });

        lblMascotas.setBackground(new java.awt.Color(255, 255, 255));
        lblMascotas.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblMascotas.setForeground(new java.awt.Color(255, 255, 255));
        lblMascotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-pets-48.png"))); // NOI18N
        lblMascotas.setText("Mascotas");
        lblMascotas.setPreferredSize(new java.awt.Dimension(150, 150));
        lblMascotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMascotasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMascotasMouseExited(evt);
            }
        });

        lblAcercaDe.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblAcercaDe.setForeground(new java.awt.Color(255, 255, 255));
        lblAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/image 19.png"))); // NOI18N
        lblAcercaDe.setText("Acerca de");
        lblAcercaDe.setPreferredSize(new java.awt.Dimension(150, 150));
        lblAcercaDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAcercaDeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAcercaDeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblMascotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSalidas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAcercaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(702, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMascotas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSalidas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAcercaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImgSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImgSalirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ImgSalirMouseClicked

    private void lblMascotasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMascotasMouseEntered
        lblMascotas.setForeground(new Color(116,116,116));
    }//GEN-LAST:event_lblMascotasMouseEntered

    private void lblMascotasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMascotasMouseExited
        lblMascotas.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lblMascotasMouseExited

    private void lblEntradasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEntradasMouseEntered
        lblEntradas.setForeground(new Color(116,116,116));
    }//GEN-LAST:event_lblEntradasMouseEntered

    private void lblEntradasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEntradasMouseExited
        lblEntradas.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lblEntradasMouseExited

    private void lblSalidasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalidasMouseEntered
        lblSalidas.setForeground(new Color(116,116,116));
    }//GEN-LAST:event_lblSalidasMouseEntered

    private void lblSalidasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalidasMouseExited
        lblSalidas.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lblSalidasMouseExited

    private void lblAcercaDeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAcercaDeMouseEntered
        lblAcercaDe.setForeground(new Color(116,116,116));
    }//GEN-LAST:event_lblAcercaDeMouseEntered

    private void lblAcercaDeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAcercaDeMouseExited
        lblAcercaDe.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lblAcercaDeMouseExited

    private void ImgSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImgSalirMouseEntered
        ImgSalir.setForeground(new Color(116,116,116));
    }//GEN-LAST:event_ImgSalirMouseEntered

    private void ImgSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImgSalirMouseExited
        ImgSalir.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_ImgSalirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
         FlatArcDarkIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImgSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAcercaDe;
    private javax.swing.JLabel lblEntradas;
    private javax.swing.JLabel lblMascotas;
    private javax.swing.JLabel lblSalidas;
    // End of variables declaration//GEN-END:variables
}
